
#Item Pickup Notifier Common Settings
[common]
	#Time in seconds to wait on login before showing notifications (Default: 10)
	#Range: 0 ~ 60
	warmupTime = 10
	#Item IDs to ignore (e.g. ["minecraft:cobblestone"])
	blacklist = []
	#If not empty, only these item IDs will be shown
	whitelist = []

